@baseUrl = http://127.0.0.1:8787
@ContentType=content-type: application/json 

# @name getCosmetic[GET]
GET {{baseUrl}}/cosmetic
{{ContentType}}

###
# @name getCosmetic[POST]
POST {{baseUrl}}/cosmetic
{{ContentType}}

{
    "category": "FACE_MASKS",
    "ingredients": ["Water","Glycerin","Ascorbic acid"]
}

###
# @name getFood[POST]
POST {{baseUrl}}/food
{{ContentType}}

{
    "category": "Drink",
    "ingredients": ["milk"]
}
